/**
 * Build-time generation of sitemap.xml and amplify-redirects.json.
 *
 * Both files used to be hand-maintained, and both had drifted:
 *   - every sitemap `lastmod` was 3.5 months stale, because the dates were
 *     literals nobody updated after content commits. Crawlers that catch a site
 *     lying about lastmod start ignoring the field, which suppresses recrawl of
 *     genuinely updated pages.
 *   - blog slugs were enumerated in four separate places, so a new post needed
 *     four synchronised edits to be crawlable.
 *
 * Both are now derived from client/src/config/routes.ts, with `lastmod` read
 * from git — the real date the page's source file last changed.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { RouteDef } from "../client/src/config/routes";

const SITE_URL = "https://poorvamcare.in";

/** Static asset extensions the SPA catch-all must not swallow. */
const ASSET_EXTS =
  "css|gif|ico|jpg|jpeg|js|png|txt|svg|woff|woff2|ttf|map|json|webp|xml";

/**
 * Last commit date for a file, as YYYY-MM-DD.
 *
 * Falls back to today when git is unavailable (e.g. a shallow CI checkout with
 * no history) or the file is untracked — a new page has legitimately just
 * changed, so today is the honest answer.
 */
function gitLastModified(file: string, repoRoot: string): string {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", file], {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(out)) return out;
  } catch {
    // fall through
  }
  return new Date().toISOString().slice(0, 10);
}

export function buildSitemap(routes: RouteDef[], repoRoot: string): string {
  const urls = routes
    .map((r) => {
      const loc = r.path === "/" ? `${SITE_URL}/` : `${SITE_URL}${r.path}`;
      const lastmod = gitLastModified(r.file, repoRoot);
      return [
        "  <url>",
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${r.changefreq}</changefreq>`,
        `    <priority>${r.priority.toFixed(1)}</priority>`,
        "  </url>",
      ].join("\n");
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-artifacts.ts from client/src/config/routes.ts.
     Do not edit by hand; changes will be overwritten on the next build. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

interface AmplifyRule {
  source: string;
  target: string;
  status: string;
  condition: null;
}

/**
 * Amplify rewrite rules, in the order Amplify evaluates them.
 *
 * Order is load-bearing. The per-route 200 rewrites must come BEFORE the SPA
 * catch-all, or the catch-all matches first and serves homepage HTML for every
 * URL — which is the bug this whole registry exists to prevent.
 */
export function buildAmplifyRedirects(routes: RouteDef[]): AmplifyRule[] {
  const legacy: AmplifyRule[] = [
    { source: "/occupationalTherapy.html", target: "/", status: "301", condition: null },
    { source: "/occupationaltherapy.html", target: "/", status: "301", condition: null },
    { source: "/speechTherapy.html", target: "/", status: "301", condition: null },
    { source: "/speechtherapy.html", target: "/", status: "301", condition: null },
    { source: "/aba.html", target: "/", status: "301", condition: null },
    { source: "/specialeducation.html", target: "/", status: "301", condition: null },
    // Strip trailing slashes so each page has one canonical URL.
    { source: "</^\\/(.+)\\/$/>", target: "/$1", status: "301", condition: null },
  ];

  const perRoute: AmplifyRule[] = routes
    .filter((r) => r.path !== "/")
    .map((r) => ({
      source: r.path,
      target: `${r.path}/index.html`,
      status: "200",
      condition: null,
    }));

  const catchAll: AmplifyRule = {
    source: `</^[^.]+$|\\.(?!(${ASSET_EXTS})$)([^.]+$)/>`,
    target: "/index.html",
    status: "200",
    condition: null,
  };

  return [...legacy, ...perRoute, catchAll];
}

/** Writes both artifacts. `distDir` receives the sitemap; redirects go to infra/. */
export function writeBuildArtifacts(
  /** Crawlable routes — get a prerender pass and an Amplify rewrite. */
  routes: RouteDef[],
  /** Indexable subset — the only ones that belong in the sitemap. */
  sitemapRoutes: RouteDef[],
  repoRoot: string,
  distDir: string,
): void {
  const sitemapPath = resolve(distDir, "sitemap.xml");
  mkdirSync(dirname(sitemapPath), { recursive: true });
  writeFileSync(sitemapPath, buildSitemap(sitemapRoutes, repoRoot), "utf8");

  const redirectsPath = resolve(repoRoot, "infra/amplify-redirects.json");
  writeFileSync(
    redirectsPath,
    JSON.stringify(buildAmplifyRedirects(routes), null, 2) + "\n",
    "utf8",
  );

  console.log(
    `\n[build-artifacts] sitemap.xml: ${sitemapRoutes.length} indexable URLs → ${sitemapPath}`,
  );
  console.log(
    `[build-artifacts] amplify-redirects.json: ${routes.length} routes → ${redirectsPath}`,
  );
  console.log(
    "[build-artifacts] REMINDER: Amplify does not read this file. Paste it into\n" +
      "                  Amplify Console → Rewrites and redirects → JSON view,\n" +
      "                  or new routes will serve homepage HTML to crawlers.\n",
  );
}
